---
name: yamllint

on:
  push:
    branches:
      - master
      - develop
      - main
  pull_request:
    branches:
      - master
      - develop
      - main
  workflow_dispatch:

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: yamllint
        uses: ibiqlik/actions-yamllint@v3
